title: My first GitHub page
author: Christoph Klesser
email: christophklesser@googlemail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  This is the most awesome page in the www, not because it is useful in any way, but I created it with GitHub pages.
twitter_username: I don't effing use twitter anymore
github_username:  cklesser

show_excerpts: true # set to false to remove excerpts on the homepage
